export const films = [
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    rating: 9.2,
    director: 'Frank Darabont',
  },
  {
    title: 'The Godfather',
    year: 1972,
    rating: 9.2,
    director: 'Francis Ford Coppola',
  },
  {
    title: 'The Godfather: Part II',
    year: 1974,
    rating: 9.0,
    director: 'Francis Ford Coppola',
  },
  {
    title: 'The Dark Knight',
    year: 2008,
    rating: 8.9,
    director: 'Christopher Nolan',
  },
  {
    title: 'Pulp Fiction',
    year: 1994,
    rating: 8.9,
    director: 'Quentin Tarantino',
  },
  {
    title: 'Schindler\'s List',
    year: 1993,
    rating: 8.9,
    director: 'Stephen Spielberg',
  },
  {
    title: '12 Angry Men',
    year: 1957,
    rating: 8.9,
    director: 'Sidney Lumet',
  },
  {
    title: 'The Good, the Bad and the Ugly',
    year: 1966,
    rating: 8.9,
    director: 'Sergio Leone',
  },
  {
    title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    rating: 8.9,
    director: 'Peter Jackson',
  },
  {
    title: 'Fight Club',
    year: 1999,
    rating: 8.8,
    director: 'David Fincher',
  },
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 2001,
    rating: 8.8,
    director: 'Peter Jackson',
  },
  {
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    year: 1980,
    rating: 8.7,
    director: 'Irvin Kershner',
  },
  {
    title: 'Forest Gump',
    year: 1994,
    rating: 8.7,
    director: 'Stephen Spielberg',
  },
  {
    title: 'Inception',
    year: 2010,
    rating: 8.7,
    director: 'Christopher Nolan',
  },
];
